=== id-sudo/RecepiesWeb/Recepies-transformed.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Recettes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="recette"/>
        <xs:element maxOccurs="unbounded" ref="categorie"/>
        <xs:element maxOccurs="unbounded" ref="sous-categorie"/>
        <xs:element maxOccurs="unbounded" ref="ingredient"/>
        <xs:element maxOccurs="unbounded" ref="produit"/>
        <xs:element maxOccurs="unbounded" ref="auteur"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="recette">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titre"/>
        <xs:element ref="photo"/>
        <xs:element ref="resume"/>
        <xs:element ref="date-publication"/>
        <xs:element ref="difficulte"/>
        <xs:element minOccurs="1" maxOccurs="20" ref="ref-ingredient"/>
        <xs:element ref="temps-preparation"/>
        <xs:element ref="temps-cuisson"/>
        <xs:element ref="temps-repos"/>
        <xs:element ref="nb-personnes"/>
        <xs:element ref="description"/>
        <xs:element minOccurs="0" ref="note"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="sous-categorie" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- identifiant de la recette -->
    <xs:key name="rid">
      <xs:selector xpath="recette"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="scr" refer="scid">
      <xs:selector xpath="recette"/>
      <xs:field xpath="@sous-categorie"></xs:field>
    </xs:keyref>
  </xs:element>
  
  <xs:element name="titre">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:minLength value="2"/>
        <xs:maxLength value="70"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="photo">
    <xs:complexType>
      <xs:attribute name="href" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="resume">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="date-publication" type="xs:date"/>
  <xs:element name="difficulte" type="xs:string"/>
  <xs:element name="temps-preparation" type="xs:NMTOKEN"/>
  <xs:element name="temps-cuisson" type="xs:string"/>
  <xs:element name="temps-repos" type="xs:string"/>
  <xs:element name="nb-personnes" type="xs:integer"/>
  
  <xs:element name="note">
    <xs:complexType/>
  </xs:element>
  
  <xs:element name="categorie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="nom-court"/>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- identifiant de la categorie -->
    <xs:key name="cid">
      <xs:selector xpath="categorie"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  
  <xs:element name="sous-categorie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="nom-court"/>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="categorie" use="required" type="xs:NCName"/>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- identifiant de la sous-categorie -->
    <xs:key name="scid">
      <xs:selector xpath="sous-categorie"/>
      <xs:field xpath="@id"/>
    </xs:key>
    <xs:keyref name="csc" refer="pid">
      <xs:selector xpath="sous-categorie"/>
      <xs:field xpath="@categorie"></xs:field>
    </xs:keyref>
  </xs:element>
  
  <xs:element name="ingredient">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="apport-nutritif"/>
        <xs:element ref="apport-energetique"/>
        <xs:element ref="saison"/>
        <xs:element ref="description"/>
        <xs:element maxOccurs="unbounded" ref="ref-recette"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="refprod" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- identifiant de l'ingrÃ©dient -->
    <xs:key name="iid">
      <xs:selector xpath="ingredient"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  
  <xs:element name="apport-nutritif" type="xs:string"/>
  <xs:element name="apport-energetique" type="xs:string"/>
  <xs:element name="saison" type="xs:string"/>
  <xs:element name="produit">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="nom-court"/>
        <xs:element maxOccurs="unbounded" ref="ref-ingredient"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- identifiant du produit -->
    <xs:key name="pid">
      <xs:selector xpath="produit"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  
  <xs:element name="auteur">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nom"/>
        <xs:element ref="pays"/>
        <xs:element ref="sexe"/>
        <xs:element ref="biographie"/>
        <xs:element maxOccurs="unbounded" ref="ref-recette"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
    <!-- identifiant de l'auteur -->
    <xs:key name="aid">
      <xs:selector xpath="auteur"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  <xs:complexType name="auteur">
    <xs:sequence>
      <xs:element ref="nom"/>
      <xs:element ref="pays"/>
      <xs:element ref="sexe"/>
      <xs:element ref="biographie"/>
      <xs:element maxOccurs="unbounded" ref="ref-recette"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" type="xs:NCName"/>
  </xs:complexType>
  <xs:element name="personne">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="auteur">
          <xs:sequence>
            <xs:element ref="titre"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="pays" type="xs:NCName"/>
  <xs:element name="sexe" type="xs:NCName"/>
  <xs:element name="biographie" type="xs:string"/>
  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="br"/>
        <xs:element ref="strong"/>
        <xs:element ref="t"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="br">
    <xs:complexType/>
  </xs:element>
  
  <xs:element name="strong" type="xs:string"/>
  <xs:element name="t" type="xs:string"/>
  
  <xs:element name="ref-ingredient">
    <xs:complexType>
      <xs:attribute name="quantite"/>
      <xs:attribute name="ref" use="required" type="xs:NCName"/>
    </xs:complexType>
    <xs:keyref name="iref" refer="iid">
      <xs:selector xpath="ref-ingredient"/>
      <xs:field xpath="@ref"></xs:field>
    </xs:keyref>
  </xs:element>
  
  <xs:element name="description">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nom" type="xs:string"/>
  <xs:element name="nom-court" type="xs:string"/>
  <xs:element name="ref-recette">
    <xs:complexType>
      <xs:attribute name="ref" use="required" type="xs:NCName"/>
    </xs:complexType>
    <xs:keyref name="rref" refer="rid">
      <xs:selector xpath="ref-recette"/>
      <xs:field xpath="@ref"></xs:field>
    </xs:keyref>
  </xs:element>
</xs:schema>

=== id-sudo/RecepiesWeb/Recepies-transformed.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Recettes
  SYSTEM "Recepies.dtd">
<Recettes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="Recepies-transformed.xsd">
   <recette id="r2830" sous-categorie="SC1">
      <titre>Cake à la tomate farcie</titre>
      <photo href="http://www.odelices.com/images/recettes/cake-a-la-tomate-farcie.jpg"/>
      <resume>
         <p>
            <t>Cake à la tomate farcie - Recettes de cuisine Ôdélices</t>
         </p>
      </resume>
      <date-publication>2011-04-24</date-publication>
      <difficulte>Très facile</difficulte>
      <ref-ingredient ref="F120" quantite="100g"/>
      <ref-ingredient ref="L300" quantite="1 cuillère à café rase"/>
      <ref-ingredient ref="L50" quantite="7,5 cl"/>
      <ref-ingredient ref="O12" quantite="1"/>
      <ref-ingredient ref="H20" quantite="1 cuillère à soupe"/>
      <ref-ingredient ref="t142" quantite="1 petite boite "/>
      <ref-ingredient ref="F10" quantite="30 g"/>
      <ref-ingredient ref="t120" quantite="6 grappes"/>
      <ref-ingredient ref="S12" quantite=""/>
      <ref-ingredient ref="Po40" quantite=""/>
      <temps-preparation>20min</temps-preparation>
      <temps-cuisson>25min</temps-cuisson>
      <temps-repos/>
      <nb-personnes>6</nb-personnes>
      <description>
         <p>1. Inciser le fond de chaque tomate et vider les graines à l'aide d'une toute petite cuillère (j'ai fait avec le manche d'une cuillère à moka).
Saler l'intérieur de chaque tomate et déposer sur un papier absorbant, elles vont dégorger.
<br/>
2. Beurrer et fariner 6 ramequins. Préchauffer le four à 180°C.<br/>
3. Faire tiédir le lait 20-30 secondes au micro-onde. Battre l'oeuf en omelette, saler et poivrer puis ajouter la farine, la levure, le lait et l'huile. 
 Ajouter le fromage râpé.<br/>
4. Dans un bol mélanger la fêta et le thon égoutté à l'aide d'une fourchette et farcir les tomates avec cette préparation.
<br/>
5. Remplir les moules avec la pâte et déposer une tomate dans chaque en l'enfonçant au deux tiers du moule.
<br/>
6. Cuire entre 20 et 25 minutes.</p>
      </description>
      <note/>
   </recette>
   <recette id="r3136" sous-categorie="SC1">
      <titre>Petits cakes au chèvre frais et myrtilles</titre>
      <photo href="http://www.odelices.com/images/recettes/petits-cakes-au-chevre-frais-et-myrtilles.jpg"/>
      <resume>
         <p>
            <t> Petits cakes au chèvre frais et myrtilles - les meilleures recettes de cuisine d'Ôdélices</t>
         </p>
      </resume>
      <date-publication>2012-04-09</date-publication>
      <difficulte>Très facile</difficulte>
      <ref-ingredient ref="F120" quantite="250 g"/>
      <ref-ingredient ref="L50" quantite="15cl"/>
      <ref-ingredient ref="O12" quantite="4"/>
      <ref-ingredient ref="H20" quantite="5cl"/>
      <ref-ingredient ref="FC20" quantite="2"/>
      <ref-ingredient ref="B200" quantite="1/4 cuillerée à café"/>
      <ref-ingredient ref="M110" quantite="100 g"/>
      <temps-preparation>10min</temps-preparation>
      <temps-cuisson>17min</temps-cuisson>
      <temps-repos/>
      <nb-personnes>6</nb-personnes>
      <description>
         <p>1. Dans un saladier, mélangez la farine, le sel, le bicarbonate, les oeufs, le lait et l'huile.<br/>
2. Quand la pâte est belle, versez-la dans de petits moules à cake huilés.<br/>
3. Répartissez sur les cakes de petits morceaux de fromage et les myrtilles.<br/>
4. Faites cuire 17 minutes à 180°C four ventilé. Piquez un cake à l'aide de la pointe d'un couteau afin de vérifier la cuisson.<br/>
5. Servez à température ambiante avec une salade croquante.<br/>
         </p>
      </description>
      <note/>
   </recette>
   <recette id="r4275" sous-categorie="SC2">
      <titre>Mozzarella panée</titre>
      <photo href="http://www.odelices.com/images/recettes/mozzarella_panee.jpg"/>
      <resume>
         <p>
            <t>Pour un soir de semaine, si vous voulez faire une salade express mais épatante, faites de la mozzarella panée ! C'est rapide, facile et très syma !
</t>
         </p>
      </resume>
      <date-publication>2015-02-08</date-publication>
      <difficulte>Très facile</difficulte>
      <ref-ingredient ref="B10" quantite="2"/>
      <ref-ingredient ref="O12" quantite="1"/>
      <ref-ingredient ref="F120" quantite="4 cuillerées à soupe"/>
      <ref-ingredient ref="CH12" quantite="1 petit bol"/>
      <temps-preparation>5min</temps-preparation>
      <temps-cuisson>5min</temps-cuisson>
      <temps-repos/>
      <nb-personnes>4</nb-personnes>
      <description>
         <p>1. Coupez les boules de mozzarella en rondelles.<br/>
2. Mettez la farine et la chapelure dans deux assiettes. Et battez l'oeuf avec une fourchette dans un bol.<br/>
3. Faites chauffer une poêle avec de l'huile.<br/>
4. Faites tremper les rondelles de mozzarella dans la farine, puis dans l'oeuf et enfin dans la chapelure.<br/>
5. Faites frire dans la poêle quelques minutes de chaque côté. Servez avec une salade verte.<br/>
         </p>
      </description>
      <note/>
   </recette>
   <recette id="r3289" sous-categorie="SC2">
      <titre>Oeuf cocotte aux marrons</titre>
      <photo href="http://www.odelices.com/images/recettes/oeuf_cocotte_aux_marrons.jpg"/>
      <resume/>
      <date-publication>2012-11-22</date-publication>
      <difficulte>Très facile</difficulte>
      <ref-ingredient ref="M9" quantite="200 g"/>
      <ref-ingredient ref="O12" quantite="4"/>
      <ref-ingredient ref="C50" quantite="4 cuillerées à soupe"/>
      <ref-ingredient ref="S12" quantite=""/>
      <ref-ingredient ref="Po40" quantite=""/>
      <temps-preparation>5min</temps-preparation>
      <temps-cuisson>15min</temps-cuisson>
      <temps-repos/>
      <nb-personnes>4</nb-personnes>
      <description>
         <p>1. Hachez grossièrement les marrons cuits. Répartissez-les dans 4 ramequins inviduels.<br/>
2. Répartissez une cuillère de crème sur les marrons.<br/>
3. Puis cassez les oeufs et ajoutez-en un dans chaque ramequin, en les posant délicatement pour ne pas casser le jaune. Salez et poivrez.<br/>
4. Placez les ramequins dans le four préchauffé à 180°C, au bain-marie. Faites cuire 15 min jusqu'à ce que le blanc soit bien pris.<br/>
5. Servez chaud, avec des mouillettes de pain grillé.<br/>
         </p>
      </description>
      <note/>
   </recette>
   <recette id="r4315" sous-categorie="SC3">
      <titre>Endives farcies au thon</titre>
      <photo href="http://www.odelices.com/images/recettes/endives_farcies_au_thon1.jpg"/>
      <resume>
         <p>
            <t>

Une salade « hébergée » dans une feuille d'endive ! Une idée gourmande qui ravira les plus jeunes qui pourront d'ailleurs vous aider à farcir les endives !</t>
         </p>
      </resume>
      <date-publication>2015-03-12</date-publication>
      <difficulte>Très facile</difficulte>
      <ref-ingredient ref="e300" quantite="2"/>
      <ref-ingredient ref="t120" quantite="2"/>
      <ref-ingredient ref="Co30" quantite="6"/>
      <ref-ingredient ref="C50" quantite="2 cuillerées à soupe"/>
      <ref-ingredient ref="M80" quantite="2 cuillerées à soupe"/>
      <ref-ingredient ref="CI10" quantite="50 g"/>
      <ref-ingredient ref="t142" quantite="10 brins"/>
      <ref-ingredient ref="S12" quantite=""/>
      <ref-ingredient ref="Po40" quantite=""/>
      <temps-preparation>15min</temps-preparation>
      <temps-cuisson/>
      <temps-repos/>
      <nb-personnes>4</nb-personnes>
      <description>
         <p>1. Lavez les tomates, coupez-les en deux et épépinez-les. Emincez finement la ciboulette.<br/>
2. Mettez dans le bol du robot le thon, les tomates, les cornichons, la crème fraîche, la moutarde et la ciboulette. Mixez le tout grossièrement pour garder quelques morceaux. Salez légèrement et poivrez éventuellement.<br/>
3. Passez les endives sous l'eau rapidement et enlevez le cône amer à la base des feuilles. Détachez les feuilles une par une, séchez-les bien.<br/>
4. Répartissez la farce dans les feuilles et servez bien frais.</p>
      </description>
      <note/>
   </recette>
   <recette id="r1241" sous-categorie="SC16">
      <titre>Moules et frites</titre>
      <photo href="http://www.odelices.com/images/recettes/moules-frites.jpg"/>
      <resume>
         <p>
            <t>	

Si vous passez par le nord, prenez le temps de déguster des frites savoureuses dans une baraque à frites et n'oubliez pas de goûter à des moules de là-bas !
Recettes extraites du livre Craquez pour la cuisine des chtis !
</t>
         </p>
      </resume>
      <date-publication>2006-06-01</date-publication>
      <difficulte>Très facile</difficulte>
      <ref-ingredient ref="MO7" quantite="2 à 3 litres"/>
      <ref-ingredient ref="oi16" quantite="2"/>
      <ref-ingredient ref="ech12" quantite="2"/>
      <ref-ingredient ref="CE5" quantite="1"/>
      <ref-ingredient ref="BEU1" quantite="20 g"/>
      <ref-ingredient ref="pom06" quantite="1 kg"/>
      <ref-ingredient ref="H20" quantite=""/>
      <ref-ingredient ref="S12" quantite=""/>
      <temps-preparation>15min</temps-preparation>
      <temps-cuisson>30 min</temps-cuisson>
      <temps-repos/>
      <nb-personnes>4</nb-personnes>
      <description>
         <p>
            <strong>Pour les moules</strong>
         </p>
         <p>1. Grattez les moules et rincez-les soigneusement.<br/>
2. Pelez et émincez les échalotes et les oignons. Faites-les revenir sans coloration dans une grande sauteuse ou une cocotte avec le beurre 2 à 3 minutes à feu vif.<br/>
3. Ajoutez les moules, le bouquet garni et le céleri. Mouillez avec le vin blanc.<br/>
4. Couvrez et laissez cuire à feu vif jusqu' à ce que les moules s'ouvrent complètement (5 minutes environ)..<br/>
5. Versez les moules et leur jus dans un plat creux. Servez avec les frites et une bière blonde.</p>
         <p>
            <strong>Pour les frites : </strong>
